#!/bin/bash

JAVA_HOME=/usr/java/default
JAVA_BIN=$JAVA_HOME/bin/java
PATH_TO_MAIN=com.cotep.bluetooth.plugin.SystemBoot

# https://code.google.com/archive/p/bluecove/wikis/Documentation.wiki
$JAVA_BIN -cp target/bluetooth-plugin-1.0-SNAPSHOT-jar-with-dependencies.jar $PATH_TO_MAIN server
